samantar_platform/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve
from . import views

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),  # NOQA
    url(r'^contact', views.contact, name = 'contact'),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

samantar_platform/forms.py
from django import forms

class FormContact(forms.Form):
	your_name = forms.CharField(label='Your name', max_length=100)
	subject = forms.CharField(max_length=100)
	message = forms.CharField(widget=forms.Textarea)
	sender = forms.EmailField()
	cc_myself = forms.BooleanField(required=False)

samantar_platform/views.py
# add to the top
from .forms import FormContact
from django.http import HttpResponse
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.conf import settings


#
def contact(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = FormContact(request.POST)
        # check whether it's valid:
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = "{0} has sent you a new message:\n\n{1}".format(sender, form.cleaned_data['message'])
           
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['shreyaagrawal0809@gmail.com']
        if cc_myself:
            recipients.append(sender)

        send_mail(subject, message, sender, recipients)
        return redirect('/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = FormContact()


    return render(request, 'contact.html', {'form': form})

samantar_platform/templates/about_us.html
{% extends "base.html" %}
{% load cms_tags %}
{% load static %}
<style type="text/css">
div .container {
    background-image:none !important;
}
text-white{
  color : black !important;
}

@media only screen and (max-width: 768px) {
  /* For mobile phones: */
  .stream-description{
    padding-left: 50px!important;
    padding-right: 50px!important;  
  }
  
}
</style>
{% block content %}
 
    <div class="container h-100 " id = "a">
      <div class="row h-40 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end" style="padding-top: 100px;">

          <h1 class="text-uppercase text-white font-weight-bold heading" style="color:black !important">{% placeholder "Heading" %}</h1>
          <hr class="divider my-4">
        </div>
       
      </div>
      <div class="row aboutus-description" style="padding-left: 100px; padding-right: 100px; ">
        <div class="aboutus-intro">{% placeholder "Introduction" %}</div>
        <div class="streams">
          <h3 class="streams-heading text-center justify-content-center" style="text-align: center;">{% placeholder "Streams" %}</h3>
          <div class="card-group">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">{% placeholder "Stream Title - 1" %}</h5>
      <p class="card-text">{% placeholder "Stream Description - 1" %}</p>
    </div>
    <div class="card-footer">
      <a href="" class="btn btn-primary">Explore</a>
    </div>
  </div>
  <div class="card">
 
    <div class="card-body">
      <h5 class="card-title">{% placeholder "Stream Title - 2" %}</h5>
      <p class="card-text">{% placeholder "Stream Description - 2" %}</p>
    </div>
    <div class="card-footer">
      <a href="" class="btn btn-primary">Explore</a>
    </div>
  </div>
  <div class="card">
  
    <div class="card-body">
      <h5 class="card-title">{% placeholder "Stream Title - 3" %}</h5>
      <p class="card-text">{% placeholder "Stream Description - 3" %}</p>
    </div>
    <div class="card-footer">
      <a href="" class="btn btn-primary">Explore</a>
    </div>
  </div>
</div>
<div class="card-group">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">{% placeholder "Stream Title - 4" %}</h5>
      <p class="card-text">{% placeholder "Stream Description - 4" %}</p>
    </div>
    <div class="card-footer">
      <a href="" class="btn btn-primary">Explore</a>
    </div>
  </div>
  <div class="card">
 
    <div class="card-body">
      <h5 class="card-title">{% placeholder "Stream Title - 5" %}</h5>
      <p class="card-text">{% placeholder "Stream Description - 5" %}</p>
    </div>
    <div class="card-footer">
      <a href="" class="btn btn-primary">Explore</a>
    </div>
  </div>
  <div class="card">
  
    <div class="card-body">
      <h5 class="card-title">{% placeholder "Stream Title - 6" %}</h5>
      <p class="card-text">{% placeholder "Stream Description - 6" %}</p>
    </div>
    <div class="card-footer">
      <a href="" class="btn btn-primary">Explore</a>
    </div>
  </div>
</div>
        </div>
      </div>
    </div>
 


{% endblock content %}

samantar_platform/templates/base.html
{% load cms_tags menu_tags sekizai_tags %}
{% load static %}
<!doctype html>
<html>
    <head>
        <title>{% block title %}{% page_attribute "page_title" %} {{ request.site.name }} {% endblock title %}</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <style type="text/css">
            .nav {
                padding-left: 0;
            }
            .nav li {
                display: inline;
                list-style-type: none;
                padding-right: 20px;
            }
            .container {
                width: 940px;
                margin: 0 auto
            }
            .content {
                float: left;
                width: 80%;
            }
            .sidebar {
                float: left;
                width: 20%;
            }


            
        </style>
        {% block css_files %}
            <link href= "{% static 'vendor/fontawesome-free/css/all.min.css' %}"  rel="stylesheet" type="text/css">

            <!-- Google Fonts -->
            <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
            <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

            <!-- Plugin CSS -->
            <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
               <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">

            <!-- Theme CSS - Includes Bootstrap -->
            <link href= "{% static 'css/creative.min.css' %}" rel="stylesheet">

            <link href= "{% static 'css/navbar.css' %}" rel="stylesheet">


            <link href= "{% static 'css/bootstrap-social.css' %}" rel="stylesheet">

        {% endblock css_files %}
        {% render_block "css" %}
    </head>
    <body>
        {% cms_toolbar %}
        {% block navbar %}
            <!-- Navigation -->
            <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">Samantar</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#streams">Streams</a>
          </li>
         <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#partners">Partners</a>
        </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#team">Team</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


        {% endblock navbar %}

       
            {% block content %}{% endblock content %}
        {% block footer %}
        <footer  style="background-color: #2c292f">
        <div class="container">
            <div class="row ">
                <div class="col-md-4 text-center text-md-left ">
                    
                    <div class="py-0">
                       <a href="https://www.civicdatalab.in/">
          <img class="logo" src="{% static 'img/logos/cdl_logo.png' %}" alt="civicdatalab" style="width: 100px;height: 100px">
        </a>
                    </div>
                </div>
                
                <div class="col-md-4 text-white text-center text-md-left ">
                    <div class="py-2 my-4">
                        <div class="py-2">
                        <a href="https://github.com/CivicDataLab"><i class="fab fa-github fa-2x text-primary mx-3"></i></a>
                        <a href="https://twitter.com/cdl_samantar"><i class="fab fa-twitter fa-2x text-danger mx-3"></i></a>
                        <a href="https://www.linkedin.com/in/civicdatalab-pvt-ltd-63a860185/"><i class="fab fa-linkedin fa-2x text-info mx-3"></i></a>
                       
                    </div>
 
           
                    </div>  
                </div>
                
                <div class="col-md-4 text-white my-4 text-center text-md-left ">
                    
        <p class="contact-text">Contact Us : </p>
        <p class="contact-email"><a class="footer-email-color" href="mailto:info@civicdatalab.in" target="_blank">samantar@civicdatalab.in</a></p>
      </div>
                </div>
                <div class="row">
      <div class="col-lg-12 text-center">
        <p class="license-text">All work under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">Creative Commons Attribution 4.0 (CC-BY)</a></p>
      </div>
            </div>  
        </div>
     </footer>
        {% endblock footer %}

        </div>

        {% block js_files %}
            <!-- Bootstrap core JavaScript -->

            <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
            <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

            <!-- Plugin JavaScript -->
            <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js'%}"></script>
            <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' "></script>

            <!-- Custom scripts for this template -->
            <script src="{% static 'js/creative.min.js' %}"></script>

        {% endblock js_files %}
        {% render_block "js" %}
    </body>
</html>

samantar_platform/templates/contact.html
{% extends "base.html" %}
{% load cms_tags %}
{% load static %}
{% block content %}

  
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lato:300,400,700'>
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">


    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
   
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">

          <h1 class="text-uppercase text-white font-weight-bold">Contact Us</h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <form id="contact-form" method="post" action="" role="form">
        {% csrf_token %}
        <div class="messages"></div>

        <div class="controls">

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="form_name">Firstname *</label>
                <input id="form_name" type="text" name="your_name" class="form-control" placeholder="Please enter your firstname *" required="required" data-error="Firstname is required.">
                <div class="help-block with-errors"></div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="form_lastname">Subject *</label>
                <input id="form_lastname" type="text" name="subject" class="form-control" placeholder="Please enter your lastname *" required="required" data-error="Lastname is required.">
                <div class="help-block with-errors"></div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="form_email">Email *</label>
                <input id="form_email" type="email" name="sender" class="form-control" placeholder="Please enter your email *" required="required" data-error="Valid email is required.">
                <div class="help-block with-errors"></div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="form_message">Message *</label>
                <textarea id="form_message" name="message" class="form-control" placeholder="Message for me *" rows="4" required data-error="Please,leave us a message."></textarea>
                <div class="help-block with-errors"></div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
               <label for="id_cc_myself" class="checkbox_cc">Cc myself:</label>
                 <input type="checkbox" name="cc_myself" id="id_cc_myself">
              </div>
            </div>
          </div>

            <div class="col-md-12">
              <input type="submit" class="btn btn-success btn-send" value="Send message" id = 'submit-button'>
            </div>
          </div>
         
        </div>
      </form>s
         
        </div>
      </div>
    
      
    </div>
 </div>
      

  

  </header>


{% endblock content %}

samantar_platform/templates/contact_form_plugin.html
{% load sekizai_tags static cms_tags %}
<html lang="en">
<head>
{% addtoblock "css" %}
<link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
{% endaddtoblock %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
   
</head>
<body>
  
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Lato:300,400,700'>


        
        <form id="contact-form" method="post" action="" role="form">
        {% csrf_token %}
        <div class="messages"></div>

        <div class="controls">

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="form_name">Firstname *</label>
                <input id="form_name" type="text" name="your_name" class="form-control" placeholder="Please enter your firstname *" required="required" data-error="Firstname is required.">
                <div class="help-block with-errors"></div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="form_lastname">Subject *</label>
                <input id="form_lastname" type="text" name="subject" class="form-control" placeholder="Please enter your lastname *" required="required" data-error="Lastname is required.">
                <div class="help-block with-errors"></div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="form_email">Email *</label>
                <input id="form_email" type="email" name="sender" class="form-control" placeholder="Please enter your email *" required="required" data-error="Valid email is required.">
                <div class="help-block with-errors"></div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="form_message">Message *</label>
                <textarea id="form_message" name="message" class="form-control" placeholder="Message for me *" rows="4" required data-error="Please,leave us a message."></textarea>
                <div class="help-block with-errors"></div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
               <label for="id_cc_myself" class="checkbox_cc">Cc myself:</label>
                 <input type="checkbox" name="cc_myself" id="id_cc_myself">
              </div>
            </div>
          </div>

            <div class="col-md-12">
              <input type="submit" class="btn btn-success btn-send" value="Send message" id = 'submit-button'>
            </div>
          </div>
         
        </div>

        </form>

      </div>

    </div>

  </div>
  

samantar_platform/templates/fullwidth.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
	{% placeholder "content" %}
{% endblock content %}

samantar_platform/templates/index.html
{% extends "base.html" %}
{% load cms_tags %}
{% load static %}


{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
 
  <title>Samantar</title>

  
 <link href= "{% static 'css/index.css' %}"  rel="stylesheet" type="text/css">

</head>

<body id="page-top">

 <div>

<div class="twitter-civic">
  
  <a class="twitter-timeline" data-width="220" data-height="400" href="https://twitter.com/cdl_samantar?ref_src=twsrc%5Etfw">Tweets by CivicDatalab</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


  </div>
  <!-- Masthead -->
  <header class="masthead">
    <div class="container h-100">
      <div class="row h-100 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end">

          <h1 class="text-uppercase text-white font-weight-bold">{% placeholder "content" %}</h1>
          <hr class="divider my-4">
        </div>
        <div class="col-lg-8 align-self-baseline">
          <p class="text-white-75 font-weight-light mb-5">Start Bootstrap can help you build better websites using the Bootstrap framework! Just download a theme and start customizing, no strings attached!</p>
          <a class="btn btn-primary btn-xl js-scroll-trigger" href="https://github.com/CivicDataLab/samantar_platform.git", target="_blank">Find Out More</a>
        </div>
      </div>
    </div>
  </header>

<br>
<br>
  <!-- Services Section -->
  <section id="portfolio" id = 'streams'>
    <div class="content-section-heading">
              
      <h2 class="text-center mt-0">Streams</h2>
      <hr class="divider my-4">
            </div>
    <div class="container-fluid p-0">
      <div class="row no-gutters">
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="/open-parallel-corpus">
            <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/1.jpg' %}" alt="">
            <div class="portfolio-box-caption">
             
              <div class="project-name">
               {% placeholder "stream 1 - Title" %}
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="/statistical-machine-translation">
            <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/2.jpg' %}" alt="">
            <div class="portfolio-box-caption">

              <div class="project-name">
                {% placeholder "stream 2 - Title" %}
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="/digital-penetration">
            <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/3.jpg' %}" alt="">
            <div class="portfolio-box-caption">

              <div class="project-name">
                 {% placeholder "stream 3 - Title" %}
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="/language-complexity-and-analysis">
            <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/4.jpg' %}" alt="">
            <div class="portfolio-box-caption">

              <div class="project-name">
                {% placeholder "stream 4 - Title" %}
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="/font-creation-and-analysis">
            <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/5.jpg' %}" alt="">
            <div class="portfolio-box-caption">

              <div class="project-name">
                 {% placeholder "stream 5 - Title" %}
              </div>
            </div>
          </a>
        </div>
        <div class="col-lg-4 col-sm-6">
          <a class="portfolio-box" href="/sociolinguistics">
            <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/6.jpg' %}" alt="">
            <div class="portfolio-box-caption p-3">

              <div class="project-name">
                 {% placeholder "stream 6 - Title" %}
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </section>

<br>
<br>


<section class="content-section section-partners" id="partners">
<h2 class="text-center mt-0">Our Partners</h2>
      <hr class="divider my-4">
    <div class="customer-logos text-center">

      <img src="{% static 'img/logos/cdl_logo.png' %}" class="img-fluid" style="width: 228px; height: 160px">
      <img src="{% static 'img/logos/pratham_books_logo.png' %}" class="img-fluid"style="width: 228px; height: 160px>
     
    </div>
    
  
</section>
  <br>
  <br>  
   <section class="content-section section-team" id="team">
        <div class="container text-center">
            <div class="content-section-heading">
              
      <h2 class="text-center mt-0">The Team</h2>
      <hr class="divider my-4">
            </div>
            <div class="row">
                <!-- Akhilesh -->
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" data-src="{% static 'img/AKR.jpg' %}" alt="Akhilesh KR" style="height: 225px; width: 100%; display: block;" src="{% static 'img/AKR.jpg' %}" data-holder-rendered="true">
                        <div class="card-body">
                            <p class="card-name">
                                Akhilesh KR
                            </p>
                            <p class="card-text">Akhilesh works on Natural Language Processing (NLP). Particularly interested in contributing to low-resource languages. He has previous experience of working on building Multilingual Chatbots and Voice Assistants for various Indian languages.</p>
          <br>
                            <div class="social-icons text-center">
                                <a href="https://github.com/akki2825" class="fa fa-github" target="_blank"></a>
                                <a href="https://twitter.com/Akhilesh_k_r" class="fa fa-twitter" target="_blank"></a>
                                <a href="https://www.linkedin.com/in/akhilesh-kr" class="fa fa-linkedin" target="_blank"></a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Deepthi -->
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" data-src="{% static 'img/DC.jpg' %} alt="Deepthi Chand Profile Pic" style="height: 225px; width: 100%; display: block;" src="{% static 'img/DC.jpg' %}" data-holder-rendered="true">
                        <div class="card-body">
                            <p class="card-name">
                                Deepthi Chand
                            </p>
                            <p class="card-text">Deepthi Chand aka DC is a data and tech evangelist. He has been instrumental as a chapter leader in defining the working operations of DataKind Bangalore. He has previously worked as a software consultant at Sahaj and Thoughtworks. <br /><br /></p>
                            <div class="social-icons text-center">
                                <a href="https://github.com/Deepthi-Chand" class="fa fa-github" target="_blank"></a>
                                <a href="https://twitter.com/eopoxf" class="fa fa-twitter" target="_blank"></a>
                                <a href="https://www.linkedin.com/in/deepthi-chand-alagandula-5415862b/" class="fa fa-linkedin" target="_blank"></a>
                            </div>
                        </div>
                    </div>
                </div>
          
            
                <!-- Shreya -->
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" data-src="img/SA.jpg" alt="Shreya Agarwal Profile Pic" style="height: 225px; width: 100%; display: block;" src="{% static 'img/SA.jpg' %}" data-holder-rendered="true">
                        <div class="card-body">
                            <p class="card-name">
                                Shreya Agrawal
                            </p>
                            <p class="card-text">Shreya Agrawal is a data fanatic who loves to scrutanize data as well as answering unanswered questions using visualizations. She also enjoy developing softwares.
                                <br>
                                <br>
                                <br>
                                <br>
                            </p>
                            <div class="social-icons text-center">
                                <a href="https://github.com/shreyaagrawal0809" target="_blank" class="fa fa-github"></a>
                                <a href="https://twitter.com/shreyabunny123" target="_blank" class="fa fa-twitter"></a>
                                <a href="https://www.linkedin.com/in/shreya-agrawal-080302" target="_blank" class="fa fa-linkedin"></a>
                            </div>
                        </div>
                    </div>
                </div>
                
                    </div>
                </div>
              
                      
                </div>
            </div>
    </section>
  </div>
</body>

</html>
{% endblock content %}

samantar_platform/templates/menu/home_menu.html
{% load i18n menu_tags cache %}
{% for child in children %}
<!-- no child pages  -->
{% if child.is_leaf_node %}
<li class="nav-item">
    <a href="{{ child.get_absolute_url }}" class="nav-link">{{child.get_menu_title }}</a>
</li>
{% endif %}
<!-- /no child pages  -->
<!-- has child pages  -->
{% if not child.is_leaf_node and child.get_descendants %} <li class="nav-item dropdown">
    <a href="{{ child.get_absolute_url }}" class=" nav-link dropdown-toggle" data-toggle="dropdown">
                {{child.get_menu_title }}<b class="caret"></b></a>
    <ul class="dropdown-menu">
        {% if child.get_descendants %}
        {% for kid in child.get_descendants %}
        
            <a href="{{ kid.get_absolute_url }}">
                <li class="dropdown-item">
                    {{kid.get_menu_title }}
                </li>
            </a>
        
        {% endfor %}
        {% endif %}
    </ul>
    </li>
    {% endif %}
    <!-- /has child pages  -->
    {% endfor %}
    <!-- /end for child -->

samantar_platform/templates/sidebar_left.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
    <div class="content">
        {% placeholder "content" %}
    </div>
{% endblock content %}

samantar_platform/templates/sidebar_right.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="content">
        {% placeholder "content" %}
    </div>
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
{% endblock content %}

samantar_platform/templates/streams.html
{% extends "base.html" %}
{% load cms_tags %}
{% load static %}
<style type="text/css">
div .container {
    background-image:none !important;
}
text-white{
  color : black !important;
}

@media only screen and (max-width: 768px) {
  /* For mobile phones: */
  .stream-description{
    padding-left: 50px!important;
    padding-right: 50px!important;  
  }
  
}
</style>
{% block content %}
 
    <div class="container h-100 " id = "a">
      <div class="row h-40 align-items-center justify-content-center text-center">
        <div class="col-lg-10 align-self-end" style="padding-top: 100px;">

          <h1 class="text-uppercase text-white font-weight-bold heading" style="color:black !important">{% placeholder "Heading" %}</h1>
          <hr class="divider my-4">
        </div>
       
      </div>
      <div class="row stream-description" style="padding-left: 100px; padding-right: 100px; ">
        <div class="stream-intro">{% placeholder "Introduction" %}</div>
        <div class="resources">
          <h3 class="resources-heading">{% placeholder "Resources" %}</h3>
          <p class="resources-points">{% placeholder "Resources Points"%}

</p>
        </div>
      </div>
    </div>
 


{% endblock content %}